# Generated by Django 4.2.6 on 2023-11-05 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reading", models.FloatField()),
                ("date", models.DateField(default=datetime.datetime.today)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meters.meter"
                    ),
                ),
            ],
        ),
    ]
