# Generated by Django 4.2.6 on 2023-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("resource", models.SmallIntegerField()),
                ("metric_prefix", models.SmallIntegerField()),
            ],
        ),
    ]
