# Generated by Django 3.1.4 on 2021-01-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_csv_file', models.FileField(upload_to='meter_csv/')),
                ('meter_raw_info', models.ManyToManyField(to='meter.Meter')),
            ],
        ),
    ]
