# Generated by Django 3.1.4 on 2021-01-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_meterinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='meter_csv_file',
            field=models.FileField(default=None, upload_to='meter_csv/'),
        ),
        migrations.DeleteModel(
            name='MeterInfo',
        ),
    ]
