# Generated by Django 3.1.5 on 2021-01-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0003_auto_20210104_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='last_reading',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_reading_date',
            field=models.DateField(default=None),
        ),
    ]
