# Generated by Django 3.1.5 on 2021-01-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_auto_20210115_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='last_reading',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='last_reading_date',
        ),
    ]
